import Head from 'next/head'
import { client } from '@/lib/client';
import { Articles, Contact, FavBooks, Features, Footer, Hero, Navbar } from '@/components'
import Link from 'next/link';

export default function Home({ books, bannerData, articelsData }) {
  
  return (
    <>
      <Head>
        <title>BookStore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='bg-grad'>
        <div className='container'>
          <Hero bannerData={bannerData} />
        </div>
      </section>
      
      <section className='bg-white'>
        <div className='container'>
          <Features />
        </div>
      </section>
      <section className='bg-white'>
        <div className='container text-center'>
          <div >
            <div className="gradient mb-4"></div>
            <h1 className='display-4'>الكتب الأكثر طلبًا</h1>
          </div>
          <div className='py-5 mb-3'>
            <FavBooks books={books} />
          </div>
          <Link href="/store">
            <button className="btn btn-outline-dark">
                  انتقل إلى معرض الكتب
            </button>
          </Link>
        </div>
      </section>
      <section className='bg-white'>
      <div className='container text-center'>
          <div>
            <div className="gradient mb-4"></div>
            <h1 className='display-4 text-center'>مقالاتنا الأخيرة</h1>
          </div>
          <div className='py-5 mb-3'>
            <Articles posts={articelsData} />
          </div>
          <Link href="/blog">
            <button className="btn btn-outline-dark text-center">
                  انتقل إلى المدونة
            </button>
          </Link>
        </div>
      </section>
      <section className='bg-dark text-white' id='contact-us'>
        <div className="gradient mb-4"></div>
        <div className='container'>
          <div>
            <h1 className='display-4 text-center'>تواصل معنا</h1>
          </div>
          <div className='p-5 mb-3'>
            <Contact />
          </div>
        </div>
      </section>
    </>
  )
}


export const getServerSideProps = async () => {
  const query = '*[_type == "bestSelling"]';
  const books = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  const articlesQuery = '*[_type == "post"]';
  const articelsData = await client.fetch(articlesQuery);

  return {
    props: { books, bannerData, articelsData }
  }
}
